### ISSUE TITLE
Problems about the mc module upon installation

### ISSUE THREAD

**Issue by shaoqx** [mms-fcul/PypKa#6] opened 2020-12-20 09:52 UTC
I'm using the latest version from `pip3 install pypka` 
I got error like this:
```
  File "C:\Users\shaoqz\AppData\Local\Programs\Python\Python36\lib\site-packages\pypka\concurrency.py", line 7, in <module>
    from mc import MCrun
ModuleNotFoundError: No module named 'mc'
```
I also tried install with `git clone` and `pip install .` to use the master branch, but still got this error.
I'm using Windows and the older version I installed doesn't have such problem.

BTW, can the program consider ion centers in the PDB structure? For example, if I have HIS and CYS coordinate to a Zn2+ will this affect the titration? If it can, how does it work?  (I found in the paper you mentioned explicit ion.)

**Comment by pedrishi** [comment] 2021-01-05 17:47
Hey @shaoqx ,

I believe this to be a duplicate of issue #2 

At the moment pypka is only supported in Linux, so in order to use it in Windows one should use WSL (which I think you were using in the past and that's why you didn't get this error). In any case, there is also a [docker image](https://hub.docker.com/r/pedrishi/pypka) with the most recent version.

Unfortunately, coordinated amino acids and metals need to be parameterized. In the paper, we mentioned explicit ions to refer to solvated Cl- and Na+ ions. I believe the best way to use pypka on a protein which such a motif would be to set the coordinated amino acids to their deprotonated states (as they likely are in the input structure already) and to not allow them to titrate by setting explicitly all the amino acids you are interested in following with the argument "sites" (or sites_<chain> if using the CLI). Since these amino acids are coordinated, they wouldn't titrate anyway, and with this trick we try to mimic the electrostatic environment for the surrounding amino acids.

Sorry for the delayed answer, I had a little Xmas vacation :P
I did see your email, but I think it is always better to answer here as it may help future users.

**Comment by shaoqx** [comment] 2021-01-06 01:06
Thank you for the response! I was using WSL all the time, sorry for the misleading description. I tried with pip again today but still wont work. I want to try the docker version, but the installation of docker is not easy. Failed many times due to the network and even my hardware. Anyway, I found my older installation of pypka, which is working well. 
For the metal center, thank you for the explanation. I see how the parameterization of coordinated amino acids is the main obstacle. It's kind of a pity that there is currently no systematic method to determine pKa of coordinating residues. Maybe I will just do the empirical way.

**Comment by pedrishi** [comment] 2021-01-06 09:23
You mean the pip install doesn't work on Windows, not not WSL, right? Your older installation is on WSL, can't you upgrade it?

I don't think you want to calculate the pKa of the coordinating residues. In this case HIS and CYS are bound to the metal center and remain in their deprotonated state, hence have no pKa as there is no equilibrium between deprotonated and protonated species.

**Comment by shaoqx** [comment] 2021-01-06 09:44
My pip install didn't work on WSL. My order version was in a different conda environment. However, I did solve it by upgrading the pip and then upgrade pypka. I think I was my pip been too old. Thanks a lot!

In a high throughput context, I want to consider more possibilities than just HIS and CYS on Zn2+. For example, when this metal center is not so electrophilic (like Mg2+) and the coordinating residue has a tight H when treated alone (like SER). Coordinating to a metal center will make the X-H bond weaker and I can't be sure if deprotonation will happen in a specific pH with such influence.

**Comment by pedrishi** [comment] 2021-01-06 10:18
Good, I am glad the problem is fixed!

About the metal center, I believe only with QM level calculations can you accurately answer that question. Best of luck!

**Closed by pedrishi** 2021-01-06 10:18 UTC

**Comment by shaoqx** [comment] 2021-01-06 10:41
Good point! Maybe QM pKa can be one of the functions of my high throughput platform. Working on that. All the Best!
