### ISSUE TITLE
No radius record for atoms

### ISSUE THREAD

**Issue by toontun** [mms-fcul/PypKa#5] opened 2020-12-01 09:59 UTC
I got lot of warnings like this: 

`"!!! WARNING: no radius record for  H    SER   617" ...` 

What does it mean? 

Thank you,
Adam

**Comment by pedrishi** [comment] 2020-12-01 10:18
Hey,

Could you provide more details?
These would be helpful:
- the input parameters
- the origin of your PDB file (did it could straight from the Protein Data Bank or is it from a simulation, if so please specify the FF used)

Best,
Pedro

**Comment by toontun** [comment] 2020-12-01 14:10
Yes ! I attached the .pdb as "antibody1.txt" and the .dat as "parameter.dat". 

The PDB file comes from a trajectory (CHARM36 for forcefield). Do I need to specify it in the parameters? 

[antibody1.txt](https://github.com/mms-fcul/PypKa/files/5623056/antibody1.txt)
[parameter.txt](https://github.com/mms-fcul/PypKa/files/5623057/parameter.txt)

Thank you for your quick reply, 
Adam

**Comment by pedrishi** [comment] 2020-12-01 15:08
Unfortunately, I wasn't able to reproduce your result. I suspect it is because you sent the structure without hydrogens. If you use pypka with this structure it will add the missing hydrogens internally and there is no mismatch in naming.

In any case, I believe you should be using the parameter "ffinput = CHARMM"

I also have a couple of comments regarding your input parameters, if I may:
- "sites_A           = all" will only compute the pKas of the amino acids in chain A. I don't know if this is what you want, but in case you want to use all chain use "sites = all"
- Considering you have a big structure with lots of titrable sites you might consider setting "ser_thr_titration = False" to ignore SER and THR amino acids. In my experience it doesn't have a significant impact on the overall results, and it provides a nice speed up to the calculations.

I noticed that in the documentation only the API usage mentions the ffinput parameter. I'll be sure to update the CLI example as well :)

**Comment by toontun** [comment] 2020-12-03 15:01
Don't you have any warnings?? With the exact same files? That's weird... Mmmm, did you use CLI or python directly? 

Thank you for your advices!

**Comment by pedrishi** [comment] 2020-12-07 10:21
I've used the CLI with the files you provided. The pypi version was slightly behind the one on github, however, I have just updated it. So please make sure you are using the latest version.

In any case, those warnings albeit annoying are not harmful. They stem from the fact that some Hydrogens are given a 0.0 radii  value (those with 0 charge) and the PB solver does not like this. It can be circumvented by assigning the radii of these atoms to 0.001, which I did... but apparently I forgot to do it in some residues. Fixed in the latest version though.

Thanks for the bug report :1st_place_medal:

**Closed** 2020-12-15 07:33 UTC

**Comment by toontun** [comment] 2020-12-15 08:29
Thank you ! Sorry for the late reply...
